//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeteringDevices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Модель
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Модель()
        {
            this.Прибор = new HashSet<Прибор>();
        }
    
        public int id_Model { get; set; }
        public string Модель1 { get; set; }
        public int id_type { get; set; }
    
        public virtual Тип Тип { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Прибор> Прибор { get; set; }
    }
}
