//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeteringDevices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Прибор
    {
        public int Учетный_номер { get; set; }
        public int Инвентарный_номер { get; set; }
        public int Id_type { get; set; }
        public int Id_model { get; set; }
        public Nullable<System.DateTime> Дата_ввода_в_эксплуатацию { get; set; }
        public Nullable<System.DateTime> Дата_поверки { get; set; }
        public string Связь_с_ответственным { get; set; }
    
        public virtual Модель Модель { get; set; }
        public virtual Тип Тип { get; set; }
    }
}
