//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeteringDevices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Прибор
    {
        public int Id_device { get; set; }
        public Nullable<int> Инвентарный_номер { get; set; }
        public int Id_models { get; set; }
        public Nullable<System.DateTime> Дата_ввода_в_экслуатацию { get; set; }
        public Nullable<System.DateTime> Дата_поверки { get; set; }
        public string Фамилия_ответственного { get; set; }
    
        public virtual Модель Модель { get; set; }
    }
}
